import type { Metadata } from "next";
import SideMenu from "./_components/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-[auto,1fr]">
      <SideMenu />
      {children}
    </div>
  );
}
