import type { Metadata } from "next";
import SideMenu from "./_components/SideMenu";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  if (!user) return redirect("/");

  return (
    <div className="grid grid-cols-[auto,1fr]">
      <SideMenu user={user} />
      {children}
    </div>
  );
}
